// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/org-service.proto

package orgservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for OrgService service

func NewOrgServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for OrgService service

type OrgService interface {
	Create(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Delete(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	List(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type orgService struct {
	c    client.Client
	name string
}

func NewOrgService(name string, c client.Client) OrgService {
	return &orgService{
		c:    c,
		name: name,
	}
}

func (c *orgService) Create(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "OrgService.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgService) Delete(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "OrgService.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgService) List(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "OrgService.List", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OrgService service

type OrgServiceHandler interface {
	Create(context.Context, *Request, *Response) error
	Delete(context.Context, *Request, *Response) error
	List(context.Context, *Request, *Response) error
}

func RegisterOrgServiceHandler(s server.Server, hdlr OrgServiceHandler, opts ...server.HandlerOption) error {
	type orgService interface {
		Create(ctx context.Context, in *Request, out *Response) error
		Delete(ctx context.Context, in *Request, out *Response) error
		List(ctx context.Context, in *Request, out *Response) error
	}
	type OrgService struct {
		orgService
	}
	h := &orgServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&OrgService{h}, opts...))
}

type orgServiceHandler struct {
	OrgServiceHandler
}

func (h *orgServiceHandler) Create(ctx context.Context, in *Request, out *Response) error {
	return h.OrgServiceHandler.Create(ctx, in, out)
}

func (h *orgServiceHandler) Delete(ctx context.Context, in *Request, out *Response) error {
	return h.OrgServiceHandler.Delete(ctx, in, out)
}

func (h *orgServiceHandler) List(ctx context.Context, in *Request, out *Response) error {
	return h.OrgServiceHandler.List(ctx, in, out)
}
